### ISSUE TITLE
How should we present errors from `revaultd` to users?

### ISSUE THREAD

**Issue by darosior** [revault/revault-gui#111]
Right now, on error the GUI would return the raw RPC error from `revaultd`. We could try to make more user-friendly errors on `revaultd` but it's going to bottleneck, as at the end of the day the RPC errors and the GUI errors aim at different things.

I believe one way to get around this would be by specifying JSONRPC error codes for classes of errors in `revaultd`, based on which the GUI could take action (like displaying a friendly user message, and optionally explaining the cause).

Opening this to gather other ideas.

**Comment by danielabrozzoni** [comment]
https://github.com/revault/revault-gui/pull/238 improved a lot the error displaying. Should we close this issue?

**Comment by darosior** [comment]
I think the current error displaying can be enhanced. But this shouldn't be the tracking issue.

If nobody has any more input on how to display errors to users conceptually, i guess we can close this.
CC @kloaec @edouardparis if you have any input (feel free to ignore)

**Comment by edouardparis** [comment]
Agree to close it
