### ISSUE TITLE
Setup Wizard design

### ISSUE THREAD

**Issue by darosior** [revault/revault-gui#116]
Summary of the meeting.

A new configuration file will be introduced for the GUI instead of using environment variables (yay for getting rid of developer-centrism!). The location of the config would not be configurable and always be the XDG config home (and respective standards for Windows / MacOS).
At startup the GUI would check whether its configuration file exists:
- If it does, and points to a valid `revaultd` config file, start the application.
- If it does, but points to an invalid (eg non-existing) `revaultd` config file, propose to either enter a valid path or setup revaultd again.
- If it does not, starts the setup wizard.

**The first screen** would make the user pick its role, either:
- Stakeholder
- Manager
- Stakeholder-manager

**The second screen** would ask the stakeholders xpubs and generate the Deposit descriptor after sorting the xpubs alphabetically in the background:
- If they are a stakeholder (or stk-manager), have "Your stakeholder xpub" and "Other Stakeholders xpubs" fields
- Else, have "Stakeholders xpubs"

**The third screen** would display a word from a fixed wordlist would be picked out of the Deposit descriptor checksum that they can cross-check.

**The fourth screen** would ask for the Unvault descriptor information:
- If they are a manager (or stk-man), have "Your manager xpub" and "Other managers xpubs" fields
- Else, have "Managers xpubs"
- In both cases have "Managers threshold", "Spending delay in blocks" (CSV), "Cosigners static keys" fields

**The fifth screen** is another word check.

**The sixth screen** would ask for the Cpfp descriptor info, with a "Managers CPFP xpubs" field.

**The seventh screen** is another word check.

**The eighth screen** is asking for the Coordinator information with a "Coordinator host" and "Coordinator Noise public key" fields (and a word check for the Noise key on the same screen).

If they are a stakeholder (or stkman):
- The next screen is asking for the Emergency address, with a word check
- The following screen is asking for the Watchtowers information (have a list you can append to), with the Host and Noise key.
Else:
- Continue to the following screens

If they are a manager (or stkman):
- A screen for filling the Cosigning servers details (check there are as many as there are stakeholders)

Finally, have a screen for configuring the connection to `bitcoind`, with the (pre-filled) path to the bitcoind datadir, interface the RPC server is listening on, and the network.

**Comment by danielabrozzoni** [comment]
> The third screen would display a word from a fixed wordlist would be picked out of the Deposit descriptor checksum that they can cross-check.

Maybe instead of creating a new screen for the words check we could display the checksum while they're typing in a box at the end of the page and instruct them to click "next" only if the checksum is correct? This way they don't have to go back and forth in case of issues

**Comment by darosior** [comment]
Maybe it can be on the same screen but i don't want to bloat it either. You won't be able to generate descriptors as they type, though (most of the time it will be syntactically or semantically incorrect and error).

**Comment by danielabrozzoni** [comment]
You can put each xpub in a separate input box and re-create the descriptor every time they change focus

**Comment by darosior** [comment]
But it will still be invalid most of the time :)

**Comment by danielabrozzoni** [comment]
I agree that a button with "generate checksums" and a button "Next" would make the screen a bit clogged. Maybe we should show a popup when the user clicks "next" with the words, and then the user has to check with friends if everything is fine, and if not just close the popup and try again?

**Comment by darosior** [comment]
We could just show the next button once all fields are filled?

1 - Nothing shown until they filled everything
2 - Either an error if they made a typo, or the word with "check that with the others stks". Below a button "I cross-checked the word"
3 - (once they clicked on "i checked the word") A wild "next" button appears !!

Actually we don't even need the "next" button, just get to the other screen. But i kinda liked my Pokemon reference so i kept it.

**Comment by edouardparis** [comment]
We dont ask how may stakeholders and managers there is, so They will add new one with a button "add stakeholder", or should we ask numbers before ?

**Comment by danielabrozzoni** [comment]
I would have the button "add stakeholder" without explicitly asking for numbers :)

-------- Original Message --------

**Comment by edouardparis** [comment]
> The sixth screen would ask for the Cpfp descriptor info, with a "Managers CPFP xpubs" field.

this is not clear for me, do we expect the user to enter manually ?
`wsh(thresh(1,pk(xpub6DoAecs8NFwcTQtUR9vGACodaa3245VuDQi3ubtE8TWV7swH7ZDWCYcuVNDRMpZjFekyU1uFPpMcZe8vgJ23h7FrZEnEtmNeFNCTgpPzJ79/*)))#4cxyfeck`

**Comment by darosior** [comment]
No, you would just gather the xpubs and call https://docs.rs/revault_tx/0.2.1/revault_tx/scripts/struct.CpfpDescriptor.html#method.new .

**Comment by darosior** [comment]
I can't remember how comes i told you to use the Miniscript compilation for that.. I'm sorry but it just seems plain wrong to me. Do you guys remember some discussion around it and why we decided to go with that?

**Comment by danielabrozzoni** [comment]
I don't remember any discussions about it, but I might be wrong.

It seems to me that in #123  the miniscript compiler is used only for generating the `DescriptorPublicKey` to be passed to the `BlablaDescriptor::new(`, why do you think it's wrong? How would you do it?

**Comment by darosior** [comment]
Unfortunately it is, as compilation is from the keys to the descriptors is non-deterministic (you can do that on 4 stks and 2 mans and they'll all end up with different descriptors).

Hmmm so i just panicked about that again and if i remember correctly it's just a transient solution until we generate the descriptors during the ceremony. It must be the reason i was fine with going with it.

**Comment by darosior** [comment]
I think we can close this? Feel free to reopen otherwise.
