### ISSUE TITLE
Send to the same address in multiple outputs

### ISSUE THREAD

**Issue by danielabrozzoni** [revault/revault-gui#130]
## Steps to reproduce:

- Create a spend transaction in the GUI
- Add recipients all having the same address:
![Revault GUI_061](https://user-images.githubusercontent.com/25042473/120036713-d621bb80-c000-11eb-819a-d7e6735b8f11.png)
- The tx created will contain only the last output entered, this because we use an HashMap for storing `(address, amount)`:
![Revault GUI_062](https://user-images.githubusercontent.com/25042473/120036832-00737900-c001-11eb-8fdb-bd3483eafb0a.png)
(notice that we should send 19 BTC to `bcrt1q6xp2ugkzrsuvd7kdqtelga5yzmfp8z9gzlj7yg` (merging the two outputs seems the most reasonable thing to do), we just send 4 to `bcrt1q6xp2ugkzrsuvd7kdqtelga5yzmfp8z9gzlj7yg` and keep the change

**Comment by danielabrozzoni** [comment]
> (merging the two outputs seems the most reasonable thing to do),

Actually, no. Better to give an error if you try to send to the same address twice

**Comment by edouardparis** [comment]
We need first to modify revaultd side (API wants map)
https://github.com/revault/revaultd/blob/master/doc/API.md#getspendtx

**Comment by danielabrozzoni** [comment]
Depends on what we want to do, I think for now it's fine if we just return an error to the user if he tries to send to the same address multiple times (so we check before calling revaultd)

**Comment by darosior** [comment]
> Actually, no. Better to give an error if you try to send to the same address twice

Is it reasonable to include this small fix for the demo release? This bug is a bit of a bummer :/

**Comment by darosior** [comment]
I would now consider this as fixed, and allowing to send to the same address in multiple outputs a feature request.

**Comment by darosior** [comment]
And i'm really not convinced we want this, tbh.

**Comment by danielabrozzoni** [comment]
I'm not sure we want this either, but I think having at least the error is fine. Maybe we should close this for now?
