### ISSUE TITLE
Confusion around the "vault" terminology 

### ISSUE THREAD

**Issue by danielabrozzoni** [revault/revault-gui#131]
We decided to call "vaults" the deposits with presigned transactions, but in the "vaults" section we still consider everything as a vault

Example:
This is the home, and it says that we have 7 vaults
![Revault GUI_063](https://user-images.githubusercontent.com/25042473/120220957-e2468c80-c23d-11eb-84f9-93c8386fab17.png)

This is the vualts section, and it says that we have 12 vaults (counting even the 5 that are just funded or securing)
![Revault GUI_064](https://user-images.githubusercontent.com/25042473/120220970-e672aa00-c23d-11eb-8a31-449b31f72c0e.png)

**Comment by edouardparis** [comment]
Good catch !
