### ISSUE TITLE
Can send "0 btc" to a recipient

### ISSUE THREAD

**Issue by danielabrozzoni** [revault/revault-gui#132]
![Revault GUI_065](https://user-images.githubusercontent.com/25042473/120236165-f1d4ce00-c25b-11eb-89e2-6e0431d2677a.png)

**Comment by danielabrozzoni** [comment]
Actually, we should check that the amounts are above the dust limit

**Comment by edouardparis** [comment]
I agree we should check the amount is not 0, but for the dust limit check I think revaultd should provide the check during the spend creation

**Comment by danielabrozzoni** [comment]
I think we should have both checks, both here and in revaultd. It's an easy check and it's definitely bad UX telling the user "ops! One of your amount is not valid!" when he has done all the process instead of just telling him right away

**Comment by danielabrozzoni** [comment]
Ah, it's not really an easy check, as it depends on the size of the output :( https://bitcoin.stackexchange.com/a/41082
ACK for checking only that the amount is != 0 then
