### ISSUE TITLE
dummy signer

### ISSUE THREAD

**Issue by edouardparis** [revault/revault-gui#162]
Emulate a hardware wallet

## Usage

take xpriv (multiple xpriv ?) as arg
Example using the password manager `pass`:

```
cargo run -- $(pass my-revault-setup/xpriv)
```

## Communication

Emulator embed a TCP server.

## Inspiration

- [Ledger Speculos](https://developers.ledger.com/docs/speculos/start-here/) 
- [Specter simulator](https://github.com/cryptoadvance/specter-diy/blob/master/docs/simulator.md)

**Comment by darosior** [comment]
Instead of having to run another binary, do you think it would be doable to have it as a startup option/config? Eg `dummy-signer=true`.

**Comment by danielabrozzoni** [comment]
All in the same binary? Do we expect to use that in a real revault setup? If not, I don't think it should be in the binary that we'll give to clients...

**Comment by darosior** [comment]
Hidden option? They could already shoot them in the foot with, say, `bitcoind` hidden options.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by danielabrozzoni** [comment]
It's not about hidden options or not, it's about not wanting to give them code that for them is useless... If no client will ever see the dummy psbtsigner, should we give that piece of code to them?

What's the pro of having everything in the same binary, anyway?

**Comment by darosior** [comment]
Not having people running YA thing for trying out.. But yeah i understand your concern. Could even be a build option :p.
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by danielabrozzoni** [comment]
> Not having people running YA thing for trying out

Damn, right

**Comment by edouardparis** [comment]
New update for this issue:
we agreed for an other binary because of the iced lack of multiple window support.
A emulated HW window will be a good example for HW manufacturers in order for them to understand our view of the sign process for revault revocation txs.
