### ISSUE TITLE
Have a REVAULTD_PATH env var 

### ISSUE THREAD

**Issue by darosior** [revault/revault-gui#18]
To set the path to the `revaultd` binary, it's not practical to have to install it globally every time...

**Comment by edouardparis** [comment]
you dont have to install it globally.
The gui will check first if revaultd is running with the given config by pinging with `getinfo` on the specified socket
so you can still run in your revaultd directory:
`cargo run --bin revaultd -- --conf $CONFIG_PATH`
and in revault-gui directory:
`REVAULTD_CONF=$CONFIG_PATH cargo run`

**Comment by darosior** [comment]
Yeah i know but i wanted to test the "GUI is starting revaultd" code path

**Comment by edouardparis** [comment]
Ok my bad, what do you think of `REVAULTD_BIN` ?

**Comment by darosior** [comment]
Sounds good :)

**Comment by danielabrozzoni** [comment]
Working on this
