### ISSUE TITLE
`--datadir <existing testnet datadir>` will launch the installer

### ISSUE THREAD

**Issue by darosior** [revault/revault-gui#188]
It should just launch the GUI with the existing datadir.

**Comment by edouardparis** [comment]
because multiple network setups can be in the same datadir, we should rely on a flag targetting the wanted network
* `--datadir <>` will check for the default mainnet setup
* `--datadir <> --testnet` will check for the testnet setup
* etc

**Comment by darosior** [comment]
Or you could do like `revaultd`, which takes only the path to a config file (which you do already) and this config file contains the network. So `datadir.push(network_name)` and then if `datadir` exists, don't launch the installer.

**Comment by edouardparis** [comment]
What I prefer in term of UX experience:
the user do `revault-gui --datadir <>` to install and then `revault-gui --datadir <> (--tesnet if he setup testnet with the instaler)` to run, He should not have to guess which file was generated to give it to gui

**Comment by darosior** [comment]
Hmm then you can already the fetch the config file if they are giving you the datadir? (if the dir actually exists)
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by edouardparis** [comment]
Users may have different gui config in datadir,
after the installer is done with a testnet setup, a `revault_gui_testnet.toml` is created.
So the user could have to choice:
1. use `--conf datadir/config_gui_testnet.toml`
2. use `--datadir datadir --testnet`
