### ISSUE TITLE
Amounts fixes

### ISSUE THREAD

**Issue by danielabrozzoni** [revault/revault-gui#248]
- [ ] We could display the decimals smaller, like in "1.00000000" the "00000000" part smaller
- [ ] ~~We could use BTC everywhere instead of "sBTC", "tBTC" etc~~ See discussion below

**Comment by darosior** [comment]
The second point was added after @kloaec 's feedback one or two demos ago.

**Comment by danielabrozzoni** [comment]
Was it? I changed it for the Miami demo as shitcoiners would tell me we were using wrapped bitcoin, but I don't think we ever had "btc" everywhere in the gui...

**Comment by darosior** [comment]
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Le mardi 2 novembre 2021 à 4:41 PM, Daniela Brozzoni ***@***.***> a écrit :

> Was it?

Yes. @edouardparis can you confirm?

**Comment by edouardparis** [comment]
No, I think we talk during a demo that user should be aware he is managing not real btc (like specifying we are on testnet or mainnet somewhere). I added the sBTC, tBTC etc as a fix but because of shitcoins it is confusing for external people.

**Comment by darosior** [comment]
Yeah so it's what i said: we added them after demo feedback.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by darosior** [comment]
That's what Bitcoin Core is doing. Green too IIRC. Maybe they write "tBTC" too, don't remember. Anyways i don't think the current way is bad, and the confusion about shitcoin can be quickly clarified.
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by danielabrozzoni** [comment]
Cool, then let's leave it like that

**Comment by edouardparis** [comment]
>  We could display the decimals smaller, like in "1.00000000" the "00000000" part smaller

Not sure if with the current price and the expected growth, we will see a lot of amount > 1 btc.
Do you agree to close it ?

**Comment by danielabrozzoni** [comment]
I don't :) It's tough for a human to distinguish by eye the amounts when they are not displayed with 8 decimals.
From example, from blockstream.info, can you distinguish immediately which output is bigger, the 2nd or the 3rd?
![Selection_173](https://user-images.githubusercontent.com/25042473/150111207-df27e9fa-588d-49b6-a07a-fca46d1aadaf.png)
It takes some time, doesn't it?
It's way easier if all the amounts have the same number of decimals:
![photo_2022-01-19_11-26-15](https://user-images.githubusercontent.com/25042473/150112314-5c94daf5-3be1-49cf-8b4b-05615809fe73.jpg)

**Comment by edouardparis** [comment]
ACK 8 decimals then :+1: I will cherry-pick your old commit in a PR
