### ISSUE TITLE
Emergency successful even with 0 funds

### ISSUE THREAD

**Issue by danielabrozzoni** [revault/revault-gui#249]
If I emergency with 0 funds, it says "Sending 0.00000000 sBTC from 0 vaults to the Emergency Deep Vault"

**Comment by edouardparis** [comment]
two solutions:
* the gui checks the amount and the number of vaults and do not display the button if 0
* We add a emergency status to revaultd getinfo that is `true` if the revaultd is in emergency mode. Gui can then display `Emergency was triggered` and do not display the Emergency button

**Comment by danielabrozzoni** [comment]
Mhh what about having the "Emergency" button, but a screen with "no vaults to send to emergency" (or something like that) if there are no secured funds?
