### ISSUE TITLE
Spend: initiate a spending: signing

### ISSUE THREAD

**Issue by darosior** [revault/revault-gui#253]
The first signing screen does not insert the signature in the PSBT.

**Comment by darosior** [comment]
Hmm can we still reproduce this @edouardparis ?

**Comment by edouardparis** [comment]
Yes, in the rare case of the hw does not add a signatures to the psbt (because it did not have the right key)
I am on it

**Comment by darosior** [comment]
Isn't the GUI checking for the presence of your own key in what you return already?
