### ISSUE TITLE
UI: stakeholder fund activation panel

### ISSUE THREAD

**Issue by edouardparis** [revault/revault-gui#29]
Stakeholder should have a panel to sign unvault transactions and activate vaults. 
 - [ ] new button action "Activate fund" or "Delegate fund" on sidebar
 - [ ] Add get_unvaul_transaction and set_unvault_transaction to revaultd client
 - [ ] new stakeholderActivateFund state and view.
 
Resuse state/signer to have a common interface to sign unvault PSBT

**Comment by darosior** [comment]
This looks like it was achieved already?

**Comment by edouardparis** [comment]
Yes https://github.com/revault/revault-gui/commit/e5137beb8843a0ca194b3d1d8b4ce84402bc0ace
