### ISSUE TITLE
Overflow in signatures needed threshold

### ISSUE THREAD

**Issue by darosior** [revault/revault-gui#291]
Happens with a 2/3 for the managers when i signed with 3 keys using the aggregated dummy signer. Don't know what the right thing to do here is.

![image](https://user-images.githubusercontent.com/22457751/146359867-e1ae4be5-ee41-43c8-be44-ff5dabc539b6.png)

**Comment by darosior** [comment]
![image](https://user-images.githubusercontent.com/22457751/146360805-3138b8ed-c05a-4bac-ad23-21618f72ca36.png)

**Comment by danielabrozzoni** [comment]
I would close this as:
1. It can happen only if you use an external software at the moment (unless I'm wrong and we do show the "Sign" button even if the transaction can be finalized, @edouardparis what do you think?)
2. Even if it does happen, saying "3/2" is not wrong in this case: you have 3 signatures but only 2 are needed. IMHO it's clear enough

**Comment by edouardparis** [comment]
GUI does not show the sign button if one of the signature is from a derived pubkey of the user master public key.
I also believe that `3/2` is not wrong, maybe we can make it even more explicit.
`Psbt has 3 signatures, two signatures are required to broadcast the transaction`

**Comment by darosior** [comment]
Ack for closing this. I agree it's not wrong.
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by danielabrozzoni** [comment]
> GUI does not show the sign button if one of the signature is from a derived pubkey of the user master public key.

Ah, so using revault-gui we can reach a 3/2... Mhh...

>  maybe we can make it even more explicit.

I like it as it is TBH. Less is more :)
