### ISSUE TITLE
ui: improve network panel

### ISSUE THREAD

**Issue by edouardparis** [revault/revault-gui#76]
- [ ] Add current network to bitcoin core card
- [ ] Add more precise sync status 
- [ ] green dot is maybe confusing
- [ ] Add a card for the coordinator, by adding a `servers` entry to `revaultd`'s `getinfo`
- [ ] If manager, add a card for the cosigners too

**Comment by darosior** [comment]
Added some bullet points for the servers too. Removing from the demo milestone since it is not critical.

**Comment by danielabrozzoni** [comment]
Should we improve it or #117 remove it?

**Comment by darosior** [comment]
> Should we improve it or #117 remove it?

Lol would be good to have an answer to this question.

**Comment by edouardparis** [comment]
remove it in favor of #117
