### ISSUE TITLE
ui: import spend_transaction must check size of imported PSBT

### ISSUE THREAD

**Issue by edouardparis** [revault/revault-gui#79]
- [ ] change https://github.com/edouardparis/revault-gui/blob/master/src/app/state/manager.rs#L441 for SpendTransaction
- [ ] update parse_psbt fro SpendTransaction::from_psbt_str 
- [ ] introduce new test (check tests/app_manager.rs)

**Comment by darosior** [comment]
`revault_tx`'s `SpendTransaction::from_psbt_str` will do exactly this :)
