### ISSUE TITLE
"Pending spend transactions" but the transaction is already spent

### ISSUE THREAD

**Issue by danielabrozzoni** [revault/revault-gui#87]
![pending_but_already_spent](https://user-images.githubusercontent.com/25042473/114189295-56ee0080-994a-11eb-96c3-4fec277ba3e6.png)
![pending_but_already_spent2](https://user-images.githubusercontent.com/25042473/114189299-57869700-994a-11eb-90ef-70c68defad3a.png)

**Comment by edouardparis** [comment]
Revaultd should remove or label spend_tx attempts once the vaults used as inputs are spent

**Comment by danielabrozzoni** [comment]
@darosior what do you think about this? Perhaps we should add some parameter to `listspendtxs` to return only the pending ones?

**Comment by darosior** [comment]
ACK. We can have a parameter making the SQL request depend on https://github.com/revault/revaultd/blob/1bb4e67f48b85120cb80cc3b86a66f31ac0cd91d/src/daemon/database/schema.rs#L99-L105 .

**Comment by danielabrozzoni** [comment]
I think we should rework this part of UI a bit. Now we have two sections:
- Pending spend transactions, which contain the spends which should be finalized
- "Funds are moving", which at the moment contains the vaults that are being spent. The problem with this section is that it shows one row per vault, so. for example:
![Revault GUI_034](https://user-images.githubusercontent.com/25042473/117112014-b7752f80-ad88-11eb-8218-83eb704bc779.png)
Ignore the first "pending spend", it's already confirmed.
In this case I'm spending two vaults and sending ~11rBTC to someone. I think I should see only one "funds are moving" row, with the amount that is being spent (and maybe we should avoid counting the change and show just what's going outside?)

What do you think? @edouardparis @darosior

**Comment by edouardparis** [comment]
Problem is what if the user is a manager who was not part of the spend signing round and does not have the spend transaction in his database ?
Same question for a stakeholder, He does not have the spend transaction.
And without spend transaction, you dont have the change output

**Comment by darosior** [comment]
I agree with Daniela that it's redundant. If the manager participated in the Spend process they shouldn't have the "Funds are moving" section. However they should not lose the ability to Cancel the spending attempt.

**Comment by danielabrozzoni** [comment]
Copy-pasting from https://github.com/revault/revaultd/pull/213
I think we should create three different sections in the home regarding spends:
1. Pending spends, which contains the spends which are awaiting signatures, and the ones not broadcasted yet (`final`, `non_final`)
2. Ongoing spends, which contains the spends we already knew, in the states `Unvaulting` `Unvaulted` `Spending` (they map to the status `Ongoing` and `Broadcasted` statuses in this PR. I left the `Ongoing` and `Broadcasted` statuses separated as they could be useful, but for the purpose of this PR I might as well merge them)
3. Unknown spends (or a better name), which contains the spends we didn't know, aka every vault in the state of `Unvaulting`, `Unvaulted`, `Spending`, but for which we didn't know the spend tx. This adds a little bit of complexity (what if we knew the spend, but a different one was broadcasted? How do we notice?) and I'm not really sure it can be made, but it would be cool to have.

**Comment by edouardparis** [comment]
Thank you for this work
I agree with 2 and 3 and I am thinking about moving 1 somewhere else maybe in the Spend modal:
So in the home you have all state of funds with moving stuff
And in the spend you have your "draft" spending transaction and "waiting other managers" transaction
![2021-05-06T10:49:41,261076506+02:00](https://user-images.githubusercontent.com/6933020/117269678-ca573500-ae58-11eb-841e-d343c26c6ee5.png)

**Comment by danielabrozzoni** [comment]
The status of this is:
- We have only the `non_final` spends in the "Pending spends" area 😍 
- ATM we are not matching the Unvault with the spends, meaning that if we see an unvault we just display it to the user like that, without any heuristic ("hey there's this unvault and it's related to this spend, and we know that because you will be the one broadcasting the spend in the first place...", for example)
- We decided to avoid moving the pending spend in the modal as we prefer having all the spends together in the home
