### ISSUE TITLE
Call for action shouldn't be displayed if there are no funds, just if there are no vaults

### ISSUE THREAD

**Issue by danielabrozzoni** [revault/revault-gui#97]
Otherwise it's quite messy when you have vaults canceled or spent but also the call for action:
![Revault GUI_010](https://user-images.githubusercontent.com/25042473/114897652-bc8e3100-9e11-11eb-84e1-e58b937304e8.png)

Also you don't really need it, if you have vaults you already know how to use Revault

**Comment by edouardparis** [comment]
closed by e142b57cd2232206e3611ffbf44ec7db6187b1f3
