### ISSUE TITLE
ui signer: add a button to show the psbt to sign as QRcode

### ISSUE THREAD

**Issue by edouardparis** [revault/revault-gui#98]

**Comment by darosior** [comment]
For what reason, and for which role do you want to add a Qr code?

**Comment by edouardparis** [comment]
CryptoAdvance hardware wallet use Qr code for air gapped communication for example.
This issue is low priority.

**Comment by darosior** [comment]
We already had this conversation a number of times, but why not restricting the HW interface to wired for the moment?
